/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EtsyCallbackRouteImport } from './routes/etsy.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EtsyCallbackRoute = EtsyCallbackRouteImport.update({
  id: '/etsy/callback',
  path: '/etsy/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/etsy/callback': typeof EtsyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/etsy/callback': typeof EtsyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/etsy/callback': typeof EtsyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/expenses' | '/listings' | '/orders' | '/settings' | '/etsy/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/expenses' | '/listings' | '/orders' | '/settings' | '/etsy/callback'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/listings'
    | '/orders'
    | '/settings'
    | '/etsy/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRoute: typeof ExpensesRoute
  ListingsRoute: typeof ListingsRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  EtsyCallbackRoute: typeof EtsyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etsy/callback': {
      id: '/etsy/callback'
      path: '/etsy/callback'
      fullPath: '/etsy/callback'
      preLoaderRoute: typeof EtsyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRoute: ExpensesRoute,
  ListingsRoute: ListingsRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  EtsyCallbackRoute: EtsyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
