/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as EtsyCallbackRouteImport } from './routes/etsy.callback'
import { Route as ApiEtsyCallbackRouteImport } from './routes/api/etsy/callback'
import { Route as ApiEtsyStartRouteImport } from './routes/api/etsy/start'
import { Route as ApiPublicEtsyTokenRefreshRouteImport } from './routes/api/public/etsy/token-refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const EtsyCallbackRoute = EtsyCallbackRouteImport.update({
  id: '/etsy/callback',
  path: '/etsy/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEtsyCallbackRoute = ApiEtsyCallbackRouteImport.update({
  id: '/api/etsy/callback',
  path: '/api/etsy/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEtsyStartRoute = ApiEtsyStartRouteImport.update({
  id: '/api/etsy/start',
  path: '/api/etsy/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEtsyTokenRefreshRoute =
  ApiPublicEtsyTokenRefreshRouteImport.update({
    id: '/api/public/etsy/token-refresh',
    path: '/api/public/etsy/token-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/etsy/callback': typeof EtsyCallbackRoute
  '/api/etsy/callback': typeof ApiEtsyCallbackRoute
  '/api/etsy/start': typeof ApiEtsyStartRoute
  '/api/public/etsy/token-refresh': typeof ApiPublicEtsyTokenRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/etsy/callback': typeof EtsyCallbackRoute
  '/api/etsy/callback': typeof ApiEtsyCallbackRoute
  '/api/etsy/start': typeof ApiEtsyStartRoute
  '/api/public/etsy/token-refresh': typeof ApiPublicEtsyTokenRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/etsy/callback': typeof EtsyCallbackRoute
  '/api/etsy/callback': typeof ApiEtsyCallbackRoute
  '/api/etsy/start': typeof ApiEtsyStartRoute
  '/api/public/etsy/token-refresh': typeof ApiPublicEtsyTokenRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/listings'
    | '/orders'
    | '/settings'
    | '/welcome'
    | '/etsy/callback'
    | '/api/etsy/callback'
    | '/api/etsy/start'
    | '/api/public/etsy/token-refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses'
    | '/listings'
    | '/orders'
    | '/settings'
    | '/welcome'
    | '/etsy/callback'
    | '/api/etsy/callback'
    | '/api/etsy/start'
    | '/api/public/etsy/token-refresh'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/listings'
    | '/orders'
    | '/settings'
    | '/welcome'
    | '/etsy/callback'
    | '/api/etsy/callback'
    | '/api/etsy/start'
    | '/api/public/etsy/token-refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRoute: typeof ExpensesRoute
  ListingsRoute: typeof ListingsRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  EtsyCallbackRoute: typeof EtsyCallbackRoute
  ApiEtsyCallbackRoute: typeof ApiEtsyCallbackRoute
  ApiEtsyStartRoute: typeof ApiEtsyStartRoute
  ApiPublicEtsyTokenRefreshRoute: typeof ApiPublicEtsyTokenRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etsy/callback': {
      id: '/etsy/callback'
      path: '/etsy/callback'
      fullPath: '/etsy/callback'
      preLoaderRoute: typeof EtsyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/etsy/callback': {
      id: '/api/etsy/callback'
      path: '/api/etsy/callback'
      fullPath: '/api/etsy/callback'
      preLoaderRoute: typeof ApiEtsyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/etsy/start': {
      id: '/api/etsy/start'
      path: '/api/etsy/start'
      fullPath: '/api/etsy/start'
      preLoaderRoute: typeof ApiEtsyStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/etsy/token-refresh': {
      id: '/api/public/etsy/token-refresh'
      path: '/api/public/etsy/token-refresh'
      fullPath: '/api/public/etsy/token-refresh'
      preLoaderRoute: typeof ApiPublicEtsyTokenRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRoute: ExpensesRoute,
  ListingsRoute: ListingsRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  EtsyCallbackRoute: EtsyCallbackRoute,
  ApiEtsyCallbackRoute: ApiEtsyCallbackRoute,
  ApiEtsyStartRoute: ApiEtsyStartRoute,
  ApiPublicEtsyTokenRefreshRoute: ApiPublicEtsyTokenRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
